\c toolshare
insert into profile values(1,1,'MickeyMouse@disney.com',false,'The Sorcerers Apprentice','The iconic, cheerful mouse who has been a Disney staple for decades',51.39,-0.4,96,'',now(),now());
insert into profile values(2,1,'Cinderella@disney.com',false,'Cindy','A kind-hearted and resilient young woman who overcomes adversity with the help of her Fairy Godmother',53.11,-2.55,60,'',now(),now());
insert into profile values(3,1,'SnowWhite@disney.com',false,'The Fairest of Them All','A gentle and pure-hearted princess who befriends seven dwarfs in the forest',53.29,-1.56,70,'',now(),now());
insert into profile values(4,1,'Ariel@disney.com',false,'The Little Mermaid','A curious and adventurous mermaid who dreams of living on land',51.71,-2.93,60,'',now(),now());
insert into profile values(5,1,'Belle@disney.com',false,'Beauty','A book-loving girl who sees beyond appearances and falls in love with a cursed prince',52.42,-0.7,49,'',now(),now());
insert into profile values(6,1,'Jasmine@disney.com',false,'The Princess of Agrabah','A spirited and independent princess who longs for freedom from her palace life',53.87,-2.92,69,'',now(),now());
insert into profile values(7,1,'Aurora@disney.com',false,'Briar Rose','A gentle and kind princess cursed to sleep until true loves kiss awakens her',51.12,-1.45,46,'',now(),now());
insert into profile values(8,1,'Rapunzel@disney.com',false,'Blondie','A long-haired princess with magical hair who embarks on a journey of self-discovery',51.17,-2.55,17,'',now(),now());
insert into profile values(9,1,'Mulan@disney.com',false,'Ping','A brave young woman who disguises herself as a man to take her fathers place in the army',52.5,-0.56,86,'',now(),now());
insert into profile values(10,1,'Pocahontas@disney.com',false,'Matoaka','A Native American woman who seeks to bridge the gap between her people and the English settlers',52.87,-2.05,79,'',now(),now());
insert into profile values(11,1,'Merida@disney.com',false,'The Brave','A skilled archer and adventurous princess who defies tradition to carve her own path',51.24,-1.57,28,'',now(),now());
insert into profile values(12,1,'Moana@disney.com',false,'The Wayfinder','A determined and courageous young woman who sets sail on a daring voyage to save her people',53.37,-2.52,59,'',now(),now());
insert into profile values(13,1,'Elsa@disney.com',false,'The Snow Queen','A queen with the magical ability to control ice and snow, who learns to embrace her powers',53.91,-2.07,10,'',now(),now());
insert into profile values(14,1,'Anna@disney.com',false,'The Ice Princess','Elsas optimistic and fearless younger sister, who embarks on a journey to mend their relationship',53.44,-0.79,16,'',now(),now());
insert into profile values(15,1,'TinkerBell@disney.com',false,'Tink','A feisty and mischievous fairy who is fiercely loyal to Peter Pan',53.45,-1.84,30,'',now(),now());
insert into profile values(16,1,'PeterPan@disney.com',false,'The Boy Who Never Grew Up','A mischievous and adventurous boy who can fly and never ages',52.07,-0.38,67,'',now(),now());
insert into profile values(17,1,'CaptainHook@disney.com',false,'James Hook','Peter Pans arch-nemesis, a cunning and fearsome pirate captain',52.91,-1.86,61,'',now(),now());
insert into profile values(18,1,'Simba@disney.com',false,'The Lion King','A young lion prince who must reclaim his throne from his villainous uncle',51.29,-0.35,39,'',now(),now());
insert into profile values(19,1,'Nala@disney.com',false,'Princess Nala','Simbas childhood friend and later his queen, known for her courage and loyalty',53.74,-0.95,51,'',now(),now());
insert into profile values(20,1,'Mufasa@disney.com',false,'King Mufasa','Simbas wise and noble father, who serves as the king of the Pride Lands',53.76,-2.79,17,'',now(),now());
insert into profile values(21,1,'Scar@disney.com',false,'The Usurper','Simbas treacherous uncle who seeks to take the throne for himself',51.21,-0.23,41,'',now(),now());
insert into profile values(22,1,'Aladdin@disney.com',false,'Prince Ali','A street-smart young man who embarks on a magical adventure with the help of a genie',51.3,-0.16,6,'',now(),now());
insert into profile values(23,1,'Genie@disney.com',false,'The Blue Phenomenon','A wisecracking and powerful genie who grants three wishes to whoever possesses his magic lamp',52.73,-2.7,97,'',now(),now());
insert into profile values(24,1,'Abu@disney.com',false,'The Monkey','Aladdins mischievous but loyal pet monkey who often gets them into trouble',52.06,-1.02,29,'',now(),now());
insert into profile values(25,1,'Jafar@disney.com',false,'The Royal Vizier','Aladdins sinister enemy who seeks ultimate power and control over Agrabah',51.51,-0.96,81,'',now(),now());
insert into profile values(26,1,'Hercules@disney.com',false,'The Son of Zeus','A mighty hero with superhuman strength who battles monsters and seeks to prove himself worthy of the gods',52.51,-0.23,21,'',now(),now());
insert into profile values(27,1,'Megara@disney.com',false,'Meg','A sarcastic and independent woman who becomes Hercules love interest',52.05,-2.49,91,'',now(),now());
insert into profile values(28,1,'Hades@disney.com',false,'Lord of the Underworld','Hercules witty and villainous uncle who seeks to overthrow the gods of Olympus',53.56,-1.09,82,'',now(),now());
insert into profile values(29,1,'Tarzan@disney.com',false,'The Ape Man','A man raised by gorillas in the jungle who must navigate both human and animal worlds',51.24,-0.14,23,'',now(),now());
insert into profile values(30,1,'Mowgli@disney.com',false,'The Man Cub','A young boy raised by wolves in the jungle, who learns the ways of the wild',52.77,-0.42,96,'',now(),now());
