\c toolshare
insert into profile values(500,'password','MickeyMouse@disney.com',false,'The Sorcerers Apprentice','The iconic, cheerful mouse who has been a Disney staple for decades',52.91,-2.72,55,'',now(),now());
insert into profile values(501,'password','Cinderella@disney.com',false,'Cindy','A kind-hearted and resilient young woman who overcomes adversity with the help of her Fairy Godmother',53.79,-2.24,10,'',now(),now());
insert into profile values(502,'password','SnowWhite@disney.com',false,'The Fairest of Them All','A gentle and pure-hearted princess who befriends seven dwarfs in the forest',51.94,-1.36,25,'',now(),now());
insert into profile values(503,'password','Ariel@disney.com',false,'The Little Mermaid','A curious and adventurous mermaid who dreams of living on land',52.9,-2.3,80,'',now(),now());
insert into profile values(504,'password','Belle@disney.com',false,'Beauty','A book-loving girl who sees beyond appearances and falls in love with a cursed prince',51.5,-0.38,100,'',now(),now());
insert into profile values(505,'password','Jasmine@disney.com',false,'The Princess of Agrabah','A spirited and independent princess who longs for freedom from her palace life',53.99,-0.55,51,'',now(),now());
insert into profile values(506,'password','Aurora@disney.com',false,'Briar Rose','A gentle and kind princess cursed to sleep until true loves kiss awakens her',51.98,-2.67,37,'',now(),now());
insert into profile values(507,'password','Rapunzel@disney.com',false,'Blondie','A long-haired princess with magical hair who embarks on a journey of self-discovery',51.1,-1.88,79,'',now(),now());
insert into profile values(508,'password','Mulan@disney.com',false,'Ping','A brave young woman who disguises herself as a man to take her fathers place in the army',53.68,-2.48,55,'',now(),now());
insert into profile values(509,'password','Pocahontas@disney.com',false,'Matoaka','A Native American woman who seeks to bridge the gap between her people and the English settlers',51.94,-0.89,49,'',now(),now());
insert into profile values(510,'password','Merida@disney.com',false,'The Brave','A skilled archer and adventurous princess who defies tradition to carve her own path',51.45,-1.13,24,'',now(),now());
insert into profile values(511,'password','Moana@disney.com',false,'The Wayfinder','A determined and courageous young woman who sets sail on a daring voyage to save her people',51.16,-1.89,85,'',now(),now());
insert into profile values(512,'password','Elsa@disney.com',false,'The Snow Queen','A queen with the magical ability to control ice and snow, who learns to embrace her powers',53.5,-1.81,31,'',now(),now());
insert into profile values(513,'password','Anna@disney.com',false,'The Ice Princess','Elsas optimistic and fearless younger sister, who embarks on a journey to mend their relationship',52.87,-0.33,81,'',now(),now());
insert into profile values(514,'password','TinkerBell@disney.com',false,'Tink','A feisty and mischievous fairy who is fiercely loyal to Peter Pan',53.09,-2.49,39,'',now(),now());
insert into profile values(515,'password','PeterPan@disney.com',false,'The Boy Who Never Grew Up','A mischievous and adventurous boy who can fly and never ages',53.63,-1.37,24,'',now(),now());
insert into profile values(516,'password','CaptainHook@disney.com',false,'James Hook','Peter Pans arch-nemesis, a cunning and fearsome pirate captain',51.67,-0.11,94,'',now(),now());
insert into profile values(517,'password','Simba@disney.com',false,'The Lion King','A young lion prince who must reclaim his throne from his villainous uncle',52.59,-2.18,14,'',now(),now());
insert into profile values(518,'password','Nala@disney.com',false,'Princess Nala','Simbas childhood friend and later his queen, known for her courage and loyalty',51.16,-1.99,37,'',now(),now());
insert into profile values(519,'password','Mufasa@disney.com',false,'King Mufasa','Simbas wise and noble father, who serves as the king of the Pride Lands',52.41,-1.16,37,'',now(),now());
insert into profile values(520,'password','Scar@disney.com',false,'The Usurper','Simbas treacherous uncle who seeks to take the throne for himself',53.43,-2.51,68,'',now(),now());
insert into profile values(521,'password','Aladdin@disney.com',false,'Prince Ali','A street-smart young man who embarks on a magical adventure with the help of a genie',51.38,-0.9,64,'',now(),now());
insert into profile values(522,'password','Genie@disney.com',false,'The Blue Phenomenon','A wisecracking and powerful genie who grants three wishes to whoever possesses his magic lamp',52.28,-1.7,41,'',now(),now());
insert into profile values(523,'password','Abu@disney.com',false,'The Monkey','Aladdins mischievous but loyal pet monkey who often gets them into trouble',52.91,-2.09,100,'',now(),now());
insert into profile values(524,'password','Jafar@disney.com',false,'The Royal Vizier','Aladdins sinister enemy who seeks ultimate power and control over Agrabah',51.8,-2.78,45,'',now(),now());
insert into profile values(525,'password','Hercules@disney.com',false,'The Son of Zeus','A mighty hero with superhuman strength who battles monsters and seeks to prove himself worthy of the gods',52.56,-1.64,34,'',now(),now());
insert into profile values(526,'password','Megara@disney.com',false,'Meg','A sarcastic and independent woman who becomes Hercules love interest',53.38,-2.21,83,'',now(),now());
insert into profile values(527,'password','Hades@disney.com',false,'Lord of the Underworld','Hercules witty and villainous uncle who seeks to overthrow the gods of Olympus',51.74,-1.64,29,'',now(),now());
insert into profile values(528,'password','Tarzan@disney.com',false,'The Ape Man','A man raised by gorillas in the jungle who must navigate both human and animal worlds',51.91,-0.94,40,'',now(),now());
insert into profile values(529,'password','Mowgli@disney.com',false,'The Man Cub','A young boy raised by wolves in the jungle, who learns the ways of the wild',51.73,-2.99,23,'',now(),now());
