\c toolshare
insert into profile values(500,1,'MickeyMouse@disney.com',false,'The Sorcerers Apprentice','The iconic, cheerful mouse who has been a Disney staple for decades',51.32,-1.65,43,'',now(),now());
insert into profile values(501,1,'Cinderella@disney.com',false,'Cindy','A kind-hearted and resilient young woman who overcomes adversity with the help of her Fairy Godmother',51.57,-3,41,'',now(),now());
insert into profile values(502,1,'SnowWhite@disney.com',false,'The Fairest of Them All','A gentle and pure-hearted princess who befriends seven dwarfs in the forest',53.19,-1.02,15,'',now(),now());
insert into profile values(503,1,'Ariel@disney.com',false,'The Little Mermaid','A curious and adventurous mermaid who dreams of living on land',51.62,-2.91,32,'',now(),now());
insert into profile values(504,1,'Belle@disney.com',false,'Beauty','A book-loving girl who sees beyond appearances and falls in love with a cursed prince',51.72,-2.34,46,'',now(),now());
insert into profile values(505,1,'Jasmine@disney.com',false,'The Princess of Agrabah','A spirited and independent princess who longs for freedom from her palace life',53.5,-1.75,35,'',now(),now());
insert into profile values(506,1,'Aurora@disney.com',false,'Briar Rose','A gentle and kind princess cursed to sleep until true loves kiss awakens her',53.77,-0.7,36,'',now(),now());
insert into profile values(507,1,'Rapunzel@disney.com',false,'Blondie','A long-haired princess with magical hair who embarks on a journey of self-discovery',52.62,-0.26,53,'',now(),now());
insert into profile values(508,1,'Mulan@disney.com',false,'Ping','A brave young woman who disguises herself as a man to take her fathers place in the army',52.39,-2.4,46,'',now(),now());
insert into profile values(509,1,'Pocahontas@disney.com',false,'Matoaka','A Native American woman who seeks to bridge the gap between her people and the English settlers',51.35,-0.63,95,'',now(),now());
insert into profile values(510,1,'Merida@disney.com',false,'The Brave','A skilled archer and adventurous princess who defies tradition to carve her own path',52.1,-2.2,86,'',now(),now());
insert into profile values(511,1,'Moana@disney.com',false,'The Wayfinder','A determined and courageous young woman who sets sail on a daring voyage to save her people',52.36,-0.18,67,'',now(),now());
insert into profile values(512,1,'Elsa@disney.com',false,'The Snow Queen','A queen with the magical ability to control ice and snow, who learns to embrace her powers',53.97,-0.24,59,'',now(),now());
insert into profile values(513,1,'Anna@disney.com',false,'The Ice Princess','Elsas optimistic and fearless younger sister, who embarks on a journey to mend their relationship',53.32,-1.59,78,'',now(),now());
insert into profile values(514,1,'TinkerBell@disney.com',false,'Tink','A feisty and mischievous fairy who is fiercely loyal to Peter Pan',53.18,-1,84,'',now(),now());
insert into profile values(515,1,'PeterPan@disney.com',false,'The Boy Who Never Grew Up','A mischievous and adventurous boy who can fly and never ages',53.36,-0.52,79,'',now(),now());
insert into profile values(516,1,'CaptainHook@disney.com',false,'James Hook','Peter Pans arch-nemesis, a cunning and fearsome pirate captain',51.67,-1.16,49,'',now(),now());
insert into profile values(517,1,'Simba@disney.com',false,'The Lion King','A young lion prince who must reclaim his throne from his villainous uncle',51.17,-1.9,37,'',now(),now());
insert into profile values(518,1,'Nala@disney.com',false,'Princess Nala','Simbas childhood friend and later his queen, known for her courage and loyalty',51.5,-2.31,23,'',now(),now());
insert into profile values(519,1,'Mufasa@disney.com',false,'King Mufasa','Simbas wise and noble father, who serves as the king of the Pride Lands',52.44,-1.83,56,'',now(),now());
insert into profile values(520,1,'Scar@disney.com',false,'The Usurper','Simbas treacherous uncle who seeks to take the throne for himself',52.76,-1.66,75,'',now(),now());
insert into profile values(521,1,'Aladdin@disney.com',false,'Prince Ali','A street-smart young man who embarks on a magical adventure with the help of a genie',52.9,-1.6,9,'',now(),now());
insert into profile values(522,1,'Genie@disney.com',false,'The Blue Phenomenon','A wisecracking and powerful genie who grants three wishes to whoever possesses his magic lamp',51.21,-2.36,51,'',now(),now());
insert into profile values(523,1,'Abu@disney.com',false,'The Monkey','Aladdins mischievous but loyal pet monkey who often gets them into trouble',53.28,-1.21,18,'',now(),now());
insert into profile values(524,1,'Jafar@disney.com',false,'The Royal Vizier','Aladdins sinister enemy who seeks ultimate power and control over Agrabah',51.44,-2.59,39,'',now(),now());
insert into profile values(525,1,'Hercules@disney.com',false,'The Son of Zeus','A mighty hero with superhuman strength who battles monsters and seeks to prove himself worthy of the gods',51.69,-1.04,53,'',now(),now());
insert into profile values(526,1,'Megara@disney.com',false,'Meg','A sarcastic and independent woman who becomes Hercules love interest',52.43,-2.28,47,'',now(),now());
insert into profile values(527,1,'Hades@disney.com',false,'Lord of the Underworld','Hercules witty and villainous uncle who seeks to overthrow the gods of Olympus',51.82,-2.24,53,'',now(),now());
insert into profile values(528,1,'Tarzan@disney.com',false,'The Ape Man','A man raised by gorillas in the jungle who must navigate both human and animal worlds',51.29,-0.95,22,'',now(),now());
insert into profile values(529,1,'Mowgli@disney.com',false,'The Man Cub','A young boy raised by wolves in the jungle, who learns the ways of the wild',52.63,-2.56,12,'',now(),now());
